version: '3.8'

services:
  backend:
    build: .
    container_name: backend_app
    ports:
      - "3000:3000"
    environment:
      - PORT=${PORT}
      - DB_HOST=${DB_HOST}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_NAME=${DB_NAME}
      - DB_PORT=${DB_PORT}
    restart: on-failure
